### PR TITLE
  ci: migrating to GitHub actions

### PR DESCRIPTION
**Pull request by JBAhire**
## Description
Migrating to GitHub actions from CircleCI as per https://github.com/hypertrace/hypertrace/issues/144

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### Documentation
- https://docs.github.com/en/free-pro-team@latest/actions

### CODE REVIEW

**Comment by aaron-steinfeld** [comment]
This whole repo we should be able to archive - it's replaced by the helm actions which include a dockerfile.

**Comment by JBAhire** [comment]
will archive after resolving ingester issue. we use bash script in ingester to validate and publish charts as it has sub-projects. so using this image there as of now. but yeah we can archive the repo. will replace that ingester script with sustainable solution or separate action in separate PR.

**Comment by aaron-steinfeld** [comment]
> will archive after resolving ingester issue. we use bash script in ingester to validate and publish charts as it has sub-projects. so using this image there as of now. but yeah we can archive the repo. will replace that ingester script with sustainable solution or separate action in separate PR.

I'm not really sure what the story behind that script is, but we can resolve that with this repo archived - the image is still available, and we don't need to publish a new one. The new actions support custom paths too, so should be fine with multiple charts in the repo.

**Comment by JBAhire** [comment]
yup. I agree.

**Comment by JBAhire** [comment]
we can archive this

**Comment by JBAhire** [comment]
closing this. @aaron-steinfeld can you please archive this repository?

**Pull request closed without merging**
